### ISSUE TITLE
union-find-0.2 does not build with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [nominolo/union-find#14]
In `base-4.17`, the `MonadFail` instance for `ST` was removed:
```console
$ cabal build
Build profile: -w ghc-9.4.4 -O1
In order, the following will be built (use -v for more details):
 - union-find-0.2 (lib:union-find) (first run)
...
src/Data/UnionFind/ST.hs:133:5: error:
    • No instance for (MonadFail (ST s))
        arising from a do statement
        with the failable pattern ‘Info info_ref1’
    • In a stmt of a 'do' block: Info info_ref1 <- readSTRef link_ref1
      In the second argument of ‘($)’, namely
        ‘do Info info_ref1 <- readSTRef link_ref1
            Info info_ref2 <- readSTRef link_ref2
            MkInfo w1 d1 <- readSTRef info_ref1
            MkInfo w2 d2 <- readSTRef info_ref2
            ....’
      In a stmt of a 'do' block:
        when (point1 /= point2)
          $ do Info info_ref1 <- readSTRef link_ref1
               Info info_ref2 <- readSTRef link_ref2
               MkInfo w1 d1 <- readSTRef info_ref1
               MkInfo w2 d2 <- readSTRef info_ref2
               ....
```
Lifted from:
- https://github.com/commercialhaskell/stackage/issues/6770

In my role as Hackage Trustee, I revised `base` to `<4.17`: https://hackage.haskell.org/package/union-find-0.2/revisions/

**Comment by andreasabel** [comment]
![grim-reaper-ghc-9 4](https://user-images.githubusercontent.com/1155218/209666993-e616ba8f-0d1f-4e8c-8a3d-6e51bf637c73.jpg)

**Comment by bergmark** [comment]
I'm getting a different error:
```
src/Ignore/Types.hs:30:10: error:
    • No instance for (Semigroup FileIgnoredChecker)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid FileIgnoredChecker’
   |
30 | instance Monoid FileIgnoredChecker where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by andreasabel** [comment]
The steps to the error I see are:
```
cabal get union-find
cd union-find-2.0
cabal build -w ghc-9.4.4 --allow-newer=union-find:base
```
